### PR TITLE
add new 'string' field type

### PR DESCRIPTION
**Pull request by aturetta**
The new parser has some initial support for escape sequences

Please look at the new test file to understand differences between 'word', 'op-quoted-string' and the new 'string'.

I suppose the new one can be a candidate to replace 'quoted-string' and 'op-quoted-string', maybe after adding some flags to better control escaping.

### CODE REVIEW

**Comment by aturetta** [comment]
How lucky!
The parser definition macros changed just one hour before my commit.... :-)

**Comment by rgerhards** [comment]
It's not a big deal I can handle that during the merge. But I would like to
review first if we really need another very broad parser. I had no time yet
to look and probably also not tomorrow,  just so that you know.

Sent from phone, thus brief.
Am 22.04.2015 18:36 schrieb "Angelo Turetta" <notifications@github.com>:

**Comment by aturetta** [comment]
In the new test file I have used one sample of Akamai access logs that is impossible to parse with the existing simpler parsers.

The new PARSER macro adjustment is already fixed by the latest commit

**Comment by rgerhards** [comment]
I had at least a quick look. Maybe we should just rename the type. "string" sounds extremly generic IMHO. How about "bash-like-string"?

**Comment by aturetta** [comment]
Well, the name I used initially was 'escaped-string', but then I realized that in could well replace the other string parsers (quoted-string and op-quoted-string), so I submitted it as just string. In fact it's exactly the parser you'd expect when looking for strings...

Whatever name you decide is fine for me, just let me know and I re-roll the branch with the new name)

**Pull request closed without merging**
