### PR TITLE
Suppress invalid param error for name to fix #270

### LINKED ISSUE #270: Float match but do not capture error
When using float and designating it to not be captured the following error is displayed when compiling with lognormalizer:
>[root@myhost test]# lognormalizer -r number.rb
liblognorm error: rulebase file number.rb[2]: invalid param for float: name

os: 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
liblognorm: liblognorm5-2.0.4-1.el7.x86_64
rules file:
>version=2
rule=:%[{"type":"float", "name":"-"}]%

Update: this is also true for the type "number"

~Regards

### PR DESCRIPTION
**Pull request by solhuebner**
Suppress invalid param error for name to fix #270 for hexnumber, float, number, date-rfc3164 and date-rfc5424.
It will just check if name is "-" to make sure that we only suppress the error message in case we do not want to capture something.

### CODE REVIEW

**Comment by rgerhards** [comment]
looks like CI needs an upgrade :-( The travis gcc error is unrelated and can be ignored for the time being.

**Comment by rgerhards** [comment]
thx for the PR, will see that I get it integrated ASAP, but right now working on upcoming rsyslog release

**Comment by solhuebner** [comment]
Thank you for considering it :)

**Comment by solhuebner** [comment]
:)

**Pull request merged**
