### PR TITLE
AIX port : added compatibility and modified lognormalizer for AIX.

### PR DESCRIPTION
**Pull request by pduveau**
Another PR for AIX. Tools are not tested on this OS (I'll do but later)

### CODE REVIEW

**Comment by pduveau** [comment]
Hi Rainer, The failed check are due to code already in the master. I don't know how to manage with them.

**Comment by rgerhards** [comment]
@pduveau sorry for the long delay. It would be great if you could rebase to now-current master. This should remove the CI issues.

**Comment by pduveau** [comment]
Hi Rainer, Now I get problems on Solaris/GCC 7 with code from the master branch. Could you have a look on this please.

**Comment by rgerhards** [comment]
Thx for the rebase. I'll have a look at the code (changes). It probably takes a few days again, as I am just back from vacation and it looks like there are some things to be looked at in the aftermath of GDPR (preparation obviously did not cover some exotic things which are now being discussed on the web...).

**Comment by rgerhards** [comment]
see PR #301 - looks like Solaris did just have a bad day ;-)

**Pull request merged**
