### PR TITLE
Adding op-quoted-string, to-string, and bugfix on docs.

### PR DESCRIPTION
**Pull request by SwissKid**
op-quoted-string:
Basically just making an additional one like quoted string that does a quoted string if the first character is ", and does word matching otherwise.
to-string:
Matching up to a string. Copied the char-to function, then modified to check for the rest of the string after the first character matches. I believe this doesn't work with hex characters (so no \x20 and such) but it removes the need for using the regex function a good amount of the time
Bugfix:
Alpha (in the docs) didn't have the correct number of "#" under it. Fixed.

### CODE REVIEW

**Comment by rgerhards** [comment]
It would be nice if you could squash commits like 0c20f96 so that the git history doesn't get clobbered.

**Comment by SwissKid** [comment]
Not completely familiar with git, I'll look into how to squash them out.

**Comment by SwissKid** [comment]
I messed with it (oh man, git rebase is scary as hell....) and I managed to remove those commits... and cause merge conflicts apparently. Merge conflicts shouldn't actually exist, might need a "unifying commit." I will attempt to fix this, and rebase to 4f5583e if it continues to have issues.

**Comment by SwissKid** [comment]
Squashed and made good with the merge. Definitely going to do stupid things like adding the file for travis-ci in another branch in the future.

**Comment by SwissKid** [comment]
Alternatively I can cancel this pull request and use https://github.com/SwissKid/liblognorm/tree/cleaner instead, which I did more aggressive rebasing on, reducing the total number of commits.

**Comment by rgerhards** [comment]
2015-01-27 11:38 GMT+01:00 Chris Schafer <notifications@github.com>:

> Alternatively I can cancel this pull request and use
> https://github.com/SwissKid/liblognorm/tree/cleaner instead, which I did
> more aggressive rebasing on, reducing the total number of commits
>

I have had a quick lock, and I think this sounds like a very good idea :)

Rainer

**Comment by SwissKid** [comment]
I hard reset the master, then fast forwarded it up the clean tree. Should
be the same commit now.
Sorry, this is the first time I've done a pull request on a large project
like this, I promise it'll be easier going next time :)

**Comment by rgerhards** [comment]
Thanks for your work! I have a little bit of a problem with the ff6f2ec commit. It looks like you merged the project master branch into yours, and done so via "git merge". It's not a show stopper, but I would probably see if I can remove that commit, in which case I need to manually merge. If you would like to look at it yourself, you can avoid this by doing a "git rebase remote-repo/master" instead of a "git merge". Again, it's not a real problem, and I know the git learning curve all too well. Just let me know if I should see and fix it or you give it a try. Again, thanks for all your help, much appreciated.

**Comment by SwissKid** [comment]
I think you could fast forward yours without having a merge if that makes
it easier. I'm not sure if I fully understand doing the rebase as you
explain it. What's the end goal?

**Comment by rgerhards** [comment]
I wanted to get rid of this commit (now in text form): "Merge branch 'master' of https://github.com/rsyslog/liblognorm". There are at least a couple of folks on the mailing list who dislike unnecessary commits, and if the branch would have been rebased before merging the current version in, that commit would not have shown up. Anyhow, I'll see now how things work out...

**Comment by SwissKid** [comment]
Thanks :) Will make sure to follow more guidelines for future pull requests

**Pull request merged**
