### PR TITLE
test solaris

### PR DESCRIPTION
**Pull request by rgerhards**

### CODE REVIEW

**Comment by andreasstieger** [comment]
This change is weird. It introduces an int function without return?

```
I: Program returns random data in a function
E: liblognorm no-return-in-nonvoid-function strndup.c:42
```

**Comment by rgerhards** [comment]
Right, should be a void. The sole point is that there is any symbol at all in the lib, else Solaris build fails. It is never used.

**Comment by andreasstieger** [comment]
I see. Could this be wrapped pre-compiler conditionals for Solaris only?

**Comment by rgerhards** [comment]
I have now just corrected the invalid type -- digging out the right OS detection is time-consuming for *me*. It's better to have this solution now. The commit comment says it all.

**Comment by rgerhards** [comment]
@andreasstieger the change is merged, please let me know if this works for you (at least as a temporary solution). Do you need a public release (or would prefer it)?

**Comment by andreasstieger** [comment]
#273 0a044b1e7a020e7a8e8d549817fd74662f927254 works, although we went for a [different solution](https://build.opensuse.org/package/view_file/openSUSE:Factory/liblognorm/liblognorm-2.0.4-no-return-in-nonvoid-function.patch?r=22). There is no need for a new release just for build fixes, proper distributions are happy to patch the source with upstream fixes or their own.

**Comment by rgerhards** [comment]
Thanks for the reply. I hope you go without the patch in the future. As time permits, I'll also see that we do a check for Solaris, but I am wading through a very long backlog.

**Pull request merged**
