### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by jjourdin**

### CODE REVIEW

**Comment by rgerhards** [comment]
I will also need to check if CI has some defects - may very well be! In any case, thx for the PR!

**Comment by rgerhards** [comment]
sry, accidentally set PR to draft - have reverted

**Comment by frikilax** [comment]
This PR concentrates 4 different features/bug fixes, that I opened in separate PRs (or were already open) : 
- #325 : Update Checkpoint Parser
- #335 : 
[IMPROVEMENT] add separator character option to 'name-value-list' parser
- #351(new) : FIX CEF PARSER
- #352 (new) : New XML parser

I think it would be simpler for anyone to try and integrate each of these PRs instead of this monolithic one

**Comment by frikilax** [comment]
@jjourdin can we close this PR ? all related changes have been proposed as separate PRs (#351, #352, #325 and #335)

**Comment by jjourdin** [comment]
Job's done, thank you

**Pull request closed without merging**
